### ISSUE TITLE
Not running on 7.4 GA31

### ISSUE THREAD

**Issue by ferdez** [jkappler/external-collection-provider#1]
Hey, 

Something has probably changed on Liferay, because this code no longer works on 7.4 GA31. When configuring a collection display with this collection provider it shows a message "An arror has occured" and the server log shows a lot of stack traces with null stuff.

HTH

**Comment by jkappler** [comment]
hi @ferdez , thanks for letting me know, will check what happened and either create a new repo or update this one

**Comment by jkappler** [comment]
hi @ferdez, created a branch 7.4.x updating the InfoFields, should work now
